language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
script: "npm run ci"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
branches:
  only:
    - master
    - "2.0.0"