swagger: '2.0'
info:
  version: 1.0.0
  title: koa-oai-router example
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /user/{userId}:
    get:
      tags:
        - User
      description: find a user by userId
      x-controller:
        - file: people
          handler: get
      parameters:
        - name: token
          in: header
          type: string
          required: true
          description: token in http header.
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: user's info
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

    post:
      tags:
        - User
      description: input a user's info
      x-controller:
        - file: people
          handler: post
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: user's info
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  User:
    title: 人
    type: object
    required:
      - name
      - sex
      - height
      - weight
    properties:
      name:
        type: string
      sex:
        type: string
        enum:
          - male
          - female
      height:
        type: integer
        format: int32
        minimum: 10
        maximum: 1000
      weight:
        type: number
        format: float
        minimum: 50
        maximum: 200
      mobile:
        type: string
  Error:
    title: Error
    type: object
    required:
      - status
      - error
    properties:
      status:
        type: integer
      path:
        type: string
      error:
        type: string
      detail:
        type: object
